{
    'name': "Multi Branch Imerex",
    'version': "14.0.1.0.0",
    'summary': """ Multiple Branch Unit Operation Setup for All 
                   Modules In Odoo""",
    'description': """Multiple Branch Unit Operation Setup for All 
                      Modules In Odoo, Branch, Branch Operations, Multiple Branch, Branch Setup""",
    'author': "CircuitMindz",
    'company': "CircuitMindz",
    'maintainer': "CircuitMindz",
    'website': "https://www.circuitmindz.com",
    'category': 'Tools',
    'depends': ['sale_management','account',
                'sale_stock', 'purchase_stock',
                'stock_account','point_of_sale','stock'],
    'data': [
        'security/branch_security.xml',
        'security/ir.model.access.csv',
        'views/res_branch_views.xml',
        'views/branch_product_template_views.xml',
        'views/branch_res_partner_views.xml',
        'views/branch_sale_order_views.xml',
        'views/branch_pos.xml',
        'views/branch_pos_config.xml',
        'views/branch_pos_order.xml',
        'views/branch_pos_payment_method.xml',
        'views/branch_pos_session.xml',
        'views/branch_purchase_order_views.xml',
        'views/branch_res_users_views.xml',
        'views/branch_stock_picking_views.xml',
        'views/branch_account_move_views.xml',
        'views/branch_account_payment_views.xml',
        'views/branch_account_journal.xml',
        'views/branch_account_views.xml',
        'views/branch_stock_warehouse_views.xml',
        'views/branch_report_template.xml',
        'views/branch_stock_scrap.xml'
    ],
    'qweb': ['static/src/xml/pos.xml'],
    # 'images': ['static/description/banner.jpg'],
    'license': "AGPL-3",
    'installable': True,
    'application': False
}
